# Generated by Django 3.0.6 on 2020-06-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('roll', models.CharField(max_length=20, verbose_name='id')),
            ],
            options={
                'db_table': 'dummy',
            },
        ),
    ]
