# Generated by Django 3.0.6 on 2020-06-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20200629_1707'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dummy',
            table='test',
        ),
    ]
