# Generated by Django 3.0.6 on 2020-06-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20200629_1719'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dummy',
            table=None,
        ),
    ]
