# Generated by Django 3.0.6 on 2020-06-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20200629_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dummy',
            options={'managed': False},
        ),
    ]
