# Generated by Django 3.0.6 on 2020-07-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20200629_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('test', models.CharField(max_length=50, verbose_name='test')),
                ('roll', models.CharField(max_length=20, verbose_name='roll')),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
